### ISSUE TITLE
Does it support multi-download from different machines at the same time?

### ISSUE THREAD

**Issue by charlesCXK** [RaSan147/py_httpserver_Ult#10]

**Comment by RaSan147** [comment]
@charlesCXK  yes of-course, multi threaded too, soo high speed download and video streaming (didn't test on lots of device, so don't know if tested on 100+ devices, but should work fine)

**Comment by charlesCXK** [comment]
Great! Thanks for your sharing such a useful tool!

**Comment by RaSan147** [comment]
If you find anything wrong or weird or misplaced or **yes bugs** please inform me.

**Comment by RaSan147** [comment]
@charlesCXK  **FYI** there was a minor typo when you filed the issue. kindly use the latest file for stability.
