### ISSUE TITLE
How to run it on Linux without root permission?

### ISSUE THREAD

**Issue by charlesCXK** [RaSan147/py_httpserver_Ult#13]

**Comment by charlesCXK** [comment]
Thanks!

**Comment by RexAckermann** [comment]
Using os.system instead of subprocess.call might work

**Comment by RaSan147** [comment]
> Using os.system instead of subprocess.call might work

subprocess.call is safer than os.system (and the issue is not here)

**Comment by RexAckermann** [comment]
adding a prompt and avoiding the installation might work

**Comment by RaSan147** [comment]
Working on it.... (Mannnn linux uses too many ways to download package, figuring out how to make them work at once)

**Comment by RexAckermann** [comment]
7zip-promt-install branch should work

**Comment by RaSan147** [comment]
Nevermind, found a way to download and use it without installing ✌️ (@RexAckermann  will need your help to check)

@charlesCXK in a day or 2 sudo/root will no longer be necessary

**Comment by RaSan147** [comment]
It seems using global package (for any Linux) causes some compatibility issue. So @charlesCXK I'll need to keep the `sudo` for now (required only once) to call apt/pkg/yum

And keeping this issue open

**Comment by RaSan147** [comment]
@charlesCXK now sudo is required only if you want to download the requirement (`sudo apt-get install p7zip-full`)
otherwise that specific feature won't work (download folder as zip)

**Comment by RaSan147** [comment]
@charlesCXK now this project no longer needs `sudo`

unless you want to run it as command
like `$./local_server.py` instead of `python3 local_server.py`
check `readme`
