### ISSUE TITLE
Auto extracting zip

### ISSUE THREAD

**Issue by RaSan147** [RaSan147/py_httpserver_Ult#5]
Ik its a messy idea. But I'll try

**Comment by RexAckermann** [comment]
There is a thing ,self extracting zip files.
But there might be some problems on android.
And it might look a bit suspicious ,kinda like
a
Virus

**Comment by RaSan147** [comment]
Self extract on server side, like upload a whole zip folder instead of making a folder and then uploading files in it.

Yeah pretty unsafe, should drop the idea or put it in the forbidden features (that should be only used for personal uses only)

**Comment by RaSan147** [comment]
No can do. Closing
