### ISSUE TITLE
issues with shabang

### ISSUE THREAD

**Issue by RexAckermann** [RaSan147/py_httpserver_Ult#57]
Can't be used as a script dirrectly due to some encoding issue:

/usr/bin/env: ‘python3\r’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines

Windows encoding is probably the issue.

**Comment by RexAckermann** [comment]
#58

**Comment by RaSan147** [comment]
Please specify the running platform
And a screenshot of the output?
I believe its a OS issue i know

**Comment by RaSan147** [comment]
Oh, its probably because windows end line with \r\n
What a pain. I'll test and patch
